SELECT  GB.TITLE, GB.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, 
        GR.CONTENTS, DATE_FORMAT(GR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM    USED_GOODS_BOARD GB, USED_GOODS_REPLY GR
WHERE   GR.BOARD_ID = GB.BOARD_ID AND
        GB.CREATED_DATE LIKE '2022-10%'
ORDER BY    GR.CREATED_DATE, GB.TITLE;
